version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: chouseikun-web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.7
    container_name: chouseikun-db
    environment:
      MYSQL_DATABASE: chousei
      MYSQL_USER: a_group
      MYSQL_PASSWORD: kickickic
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
